# Generated by Django 5.2.6 on 2025-11-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('usado', models.BooleanField(default=False)),
            ],
        ),
    ]
