# Generated by Django 5.2.6 on 2025-11-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='funcion',
            field=models.CharField(choices=[('primera', 'Primera'), ('segunda', 'Segunda')], default='primera', max_length=7),
        ),
    ]
