# Generated by Django 5.2.6 on 2025-11-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_codigo_funcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigo',
            name='usado',
        ),
        migrations.AddField(
            model_name='codigo',
            name='entradas_disponibles',
            field=models.IntegerField(default=2),
        ),
    ]
